version: '3.4'
services:
  snippetbox:
    restart: always
    depends_on:
      - snippetboxdb
    ports:
      - "4000:4000"
    build:
      dockerfile: Dockerfile
      context: .
  snippetboxdb:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: yerzak
      POSTGRES_PASSWORD: 12345yer
      POSTGRES_DB: snippetbox
    ports:
      - "5432:5432"
    volumes:
      - ./docsql.sql:/docker-entrypoint-initdb.d/init.sql